CI: disable test-wine64

diff --git a/.github/workflows/mupif.yml b/.github/workflows/mupif.yml
--- a/.github/workflows/mupif.yml
+++ b/.github/workflows/mupif.yml
@@ -48,36 +48,36 @@ jobs:
         set -euo pipefail
         cd examples; ./runex.py --codecov 2>&1 | ../tools/grcat-mupif
 
-  test-wine64:
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        python-version: [3.8]
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: |
-        sudo apt-get update && sudo apt-get install wine64 wine python3-pip dos2unix
-        python -m pip install wenv
-        echo '{"arch":"win64","pythonversion":"3.8.5"}' > ~/.wenv.json
-        wenv init
-        wenv pip install --only-binary=pyrsistent -r requirements.txt
-    - name: unit tests
-      timeout-minutes: 1
-      run: |
-        set -euo pipefail
-        # wenv python -m nose -v --rednose --traverse-namespace 2>&1 | dos2unix | tools/grcat-mupif
-        wenv python -m pytest -v mupif/tests 2>&1 | dos2unix | tools/grcat-mupif
-    - name: examples
-      timeout-minutes: 2 # normally about 50s
-      run: |
-        set -euo pipefail
-        # skip tests 4 and 7, somehow fail under wine
-        cd examples; wenv python runex.py 1 2 3 5 6 8 2>&1 | dos2unix | ../tools/grcat-mupif
+#  test-wine64:
+#    runs-on: ubuntu-20.04
+#    strategy:
+#      matrix:
+#        python-version: [3.8]
+#    steps:
+#    - uses: actions/checkout@v2
+#    - name: Set up Python ${{ matrix.python-version }}
+#      uses: actions/setup-python@v2
+#      with:
+#        python-version: ${{ matrix.python-version }}
+#    - name: Install dependencies
+#      run: |
+#        sudo apt-get update && sudo apt-get install wine64 wine python3-pip dos2unix
+#        python -m pip install wenv
+#        echo '{"arch":"win64","pythonversion":"3.8.5"}' > ~/.wenv.json
+#        wenv init
+#        wenv pip install --only-binary=pyrsistent -r requirements.txt
+#    - name: unit tests
+#      timeout-minutes: 1
+#      run: |
+#        set -euo pipefail
+#        # wenv python -m nose -v --rednose --traverse-namespace 2>&1 | dos2unix | tools/grcat-mupif
+#        wenv python -m pytest -v mupif/tests 2>&1 | dos2unix | tools/grcat-mupif
+#    - name: examples
+#      timeout-minutes: 2 # normally about 50s
+#      run: |
+#        set -euo pipefail
+#        # skip tests 4 and 7, somehow fail under wine
+#        cd examples; wenv python runex.py 1 2 3 5 6 8 2>&1 | dos2unix | ../tools/grcat-mupif
 
   test-docker-VPN:
     runs-on: ubuntu-20.04
