actions: split off wine64 test, run linux in parallel (maybe)

diff --git a/.github/workflows/mupif.yml b/.github/workflows/mupif.yml
--- a/.github/workflows/mupif.yml
+++ b/.github/workflows/mupif.yml
@@ -16,7 +16,7 @@ jobs:
       matrix:
         python-version: [ 3.8, 3.9 ]
         # fail-fast: 0
-      max-parallel: 1 # avoid localhost conflicts
+      # max-parallel: 1 # avoid localhost conflicts
     steps:
     - uses: actions/checkout@v2
     - name: Set up Python ${{ matrix.python-version }}
@@ -47,21 +47,42 @@ jobs:
         set -euo pipefail
         nosetests --rednose --force-color -v --with-coverage 2>&1 | tools/grcat-mupif
         codecov -F unittests
-    - name: nosetests (win64)
-      timeout-minutes: 1
-      run: |
-        set -euo pipefail
-        wenv nosetests --rednose -v  2>&1 | dos2unix | tools/grcat-mupif
     - name: examples (native)
       timeout-minutes: 2 # normally about 35s
       run: |
         set -euo pipefail
         cd examples; ./runex.py --codecov 2>&1 | ../tools/grcat-mupif
-    - name: examples (win32)
+
+  test-wine64:
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        python-version: [3.8]
+    steps:
+    - uses: actions/checkout@v2
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install dependencies
+      run: |
+        sudo apt-get install wine64 wine python3-pip dos2unix
+        python -m pip install -q wenv
+        echo '{"arch":"win64","pythonversion":"3.8.5"}' > ~/.wenv.json
+        wenv init
+        wenv pip install -q --only-binary=pyrsistent -r requirements.txt
+    - name: nosetests
+      timeout-minutes: 1
+      run: |
+        set -euo pipefail
+        wenv nosetests --rednose -v  2>&1 | dos2unix | tools/grcat-mupif
+    - name: examples
       timeout-minutes: 2 # normally about 50s
       run: |
         set -euo pipefail
+        # skip test 7, somehow fails under wine
         cd examples; ./runex.py --wenv=all 1 2 3 4 5 6 8 2>&1 | dos2unix | ../tools/grcat-mupif
+
   test-windows:
     runs-on: windows-latest
     strategy:
@@ -88,4 +109,4 @@ jobs:
       run: python3 examples/runex.py
       # 2>&1 | python3 -u ../tools/grcat-mupif
 
-      
+
